
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: ssg-test
        ports:
            - 5432:5432
        volumes:
            - ssg-test:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    ssg-test:
        driver: local